apiVersion: v1
kind: Service
metadata:
  name: the-pick-ui
  labels:
    app: the-pick-ui
spec:
  selector:
    app: the-pick-ui
  type: ClusterIP
  ports:
    - name: the-pick-ui
      protocol: TCP
      port: 80
      targetPort: 80

