apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: the-pick-ui
  annotations:
    kubernetes.io/ingress.global-static-ip-name: apithepickspace
    networking.gke.io/managed-certificates: thepickspace
spec:
  rules:
    - host: thepick.space
      http:
        paths:
          - path: "/"
            backend:
              serviceName: the-pick-ui
              servicePort: 80
          - path: "/api"
            pathType: Prefix
            backend:
              serviceName: the-pick-api
              servicePort: 80
